config/routes.rb
Rails.application.routes.draw do
  get 'home', to: 'levels#home'
  get 'level1', to: 'levels#level1'
  get 'level2', to: 'levels#level2'
  get 'level3', to: 'levels#level3'
  get 'level4', to: 'levels#level4'
  get 'level5', to: 'levels#level5'
  get 'level7', to: 'levels#level7'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'levels#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_locale
    def default_url_options
        { locale: I18n.locale == I18n.default_locale ? nil : I18n.locale }
    end

    def set_locale
        I18n.locale = params[:locale] || I18n.default_locale
    end

end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController
  def home
  end

  def level1
  end

  def level2
  end

  def level3
  end

  def level4
  end

  def level5
  end

  def level6
  end

  def level7
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MansCels</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href='https://fonts.googleapis.com/css?family=Press Start 2P' rel='stylesheet'>
    <link href="https://unpkg.com/nes.css/css/nes-core.min.css" rel="stylesheet" />
    <style>
    body {
      font-family: 'Press Start 2P';font-size: 21px;
    }
    </style>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/levels/home.html.erb
<style>
#title{
  font-size: 29px;
  color: #cce4f2;
  position: absolute;
  left: 23%;
  bottom: 42%;
  
}

.title-centering{
  font-size: 31px;
  color: #cce4f2;
  position: absolute;
  left: 37%;
  bottom: 49%;
}

#container{
  position: absolute;
  height: 100%;
  width: 100%;
  background-image: url("Mans_cels_Home_1(2).gif");
  background-size: cover;
}

#button{
  background-color: #cce4f2;
  color: black;
  font-size: 29px;
  position: absolute;
  left: 50%;
  bottom: 32%;
  text-decoration: none;
}

#locale{
  background-color: #cce4f2;
  color: black;
  font-size: 29px;
  position: absolute;
  left: 65%;
  bottom: 32%;
  text-decoration: none;
}


</style>
<div class="nes-container with-title is-centered" id="container">
  <div class="title-centering">
    <h1><%= t 'journey' %></h1>
  </div>

  <div id="title">
    <h2><%= t 'other_title' %><h2>
  </div>

  <div>
    <%=link_to t('begin'), level1_path, class: "nes-btn is-normal", id: "button"%>
    <% if I18n.locale == I18n.default_locale %>
      <%=link_to t('locale_button'), home_path(:locale=> 'en'), class: "nes-btn is-normal", id: "locale"%>
    <% else %>  
      <%=link_to t('locale_button'), home_path(:locale=> 'lv'), class: "nes-btn is-normal", id: "locale"%>
    <% end %>
  </div>
</div>

app/views/levels/level1.html.erb
<style>
.outer{
    padding: 30px;
}

.section_8bit{
  font-size: 19px;
  width: 95%;
  height: 15%;
  float: left;
  border-left: 10px solid #f0eded;
  border-right: 10px solid #f0eded;
  position: absolute;
  bottom: 4%;
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
  background: #000000;
  overflow:auto;
}
 
.section_8bit .wrapper{
  display: block;
  color: #ffffff;
  padding: 10px;
  padding-left: 35px;
  margin: -10px 0;
  border-top: 10px solid #f0eded;
  border-bottom: 10px solid #f0eded;
}
 
.section_8bit::before,
.section_8bit::after,
.section_8bit .wrapper::before,
.section_8bit .wrapper::after{
  content: '';
  width: 10px;
  height: 10px;
  display: block;
  position: absolute;
  background: #f0eded;
}
.section_8bit::before{ top: -5px; left: -5px; }
.section_8bit::after{ top: -5px; right: -5px; }
.section_8bit .wrapper::before{ bottom: -5px; left: -5px; }
.section_8bit .wrapper::after{ bottom: -5px; right: -5px; }

.button-arrow-right {
  color: #000000;
  position: absolute;
  bottom: 51%;
  box-sizing: border-box;
  font-size: 100px;
  text-decoration: none;
  right: 20px;

}

.button-arrow-right:hover, .button-arrow-right:active{
  color: #000000;
  text-decoration: none;
}

.button-arrow-left {
  color: #000000;
  position: absolute;
  bottom: 51%;
  box-sizing: border-box;
  font-size: 100px;
  text-decoration: none;
  left: 20px;

}

.button-arrow-left:hover, .button-arrow-left:active{
  color: #000000;
  text-decoration: none;
}
#container{
  position: absolute;
  height: 100%;
  width: 100%;
  background-image: url("Cels_uz_Staciju.gif");
  background-size: cover;
}
</style>
<div id="container">
  <section class="outer">
  <section class="section_8bit">
    <div class="wrapper">
      <h1><%= t 'station_name' %></h1>
      <p><%= t 'station_desc' %></p>
    </div>
  </section>

  <%= link_to ">", home_path, method: :get, class: "button-arrow-right" %>
  <%= link_to "<", level2_path, method: :get, class: "button-arrow-left" %>
  </section>
</div>

app/views/levels/level2.html.erb
<style>
.outer{
    padding: 30px;
}

.section_8bit{
  font-size: 19px;
  width: 95%;
  height: 15%;
  float: left;
  border-left: 10px solid #f0eded;
  border-right: 10px solid #f0eded;
  position: absolute;
  bottom: 4%;
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
  background: #000000;
  overflow:auto;
}
 
.section_8bit .wrapper{
  display: block;
  color: #ffffff;
  padding: 10px;
  padding-left: 35px;
  margin: -10px 0;
  border-top: 10px solid #f0eded;
  border-bottom: 10px solid #f0eded;
}
 
.section_8bit::before,
.section_8bit::after,
.section_8bit .wrapper::before,
.section_8bit .wrapper::after{
  content: '';
  width: 10px;
  height: 10px;
  display: block;
  position: absolute;
  background: #f0eded;
}
.section_8bit::before{ top: -5px; left: -5px; }
.section_8bit::after{ top: -5px; right: -5px; }
.section_8bit .wrapper::before{ bottom: -5px; left: -5px; }
.section_8bit .wrapper::after{ bottom: -5px; right: -5px; }

.button-arrow-right {
  color: #000000;
  position: absolute;
  bottom: 51%;
  box-sizing: border-box;
  font-size: 100px;
  text-decoration: none;
  right: 20px;

}

.button-arrow-right:hover, .button-arrow-right:active{
  color: #000000;
  text-decoration: none;
}

.button-arrow-left {
  color: #000000;
  position: absolute;
  bottom: 51%;
  box-sizing: border-box;
  font-size: 100px;
  text-decoration: none;
  left: 20px;

}

.button-arrow-left:hover, .button-arrow-left:active{
  color: #000000;
  text-decoration: none;
}

#container{
  position: absolute;
  height: 100%;
  width: 100%;
  background-image: url("Stacija.gif");
  background-size: cover;
}
</style>
<div id="container">
<section class="outer">
  <section class="section_8bit">
    <div class="wrapper">
      <h1><%= t 'at_station' %></h1>
      <p><%= t 'at_station_desc' %></p>
    </div>
  </section>

    <%= link_to ">", level1_path, method: :get, class: "button-arrow-right" %>
    <%= link_to "<", level3_path, method: :get, class: "button-arrow-left" %>
  </section>
</div>

app/views/levels/level3.html.erb
<style>
.outer{
    padding: 30px;
}

.section_8bit{
  font-size: 19px;
  width: 95%;
  height: 15%;
  float: left;
  border-left: 10px solid #f0eded;
  border-right: 10px solid #f0eded;
  position: absolute;
  bottom: 4%;
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
  background: #000000;
  overflow:auto;
}
 
.section_8bit .wrapper{
  display: block;
  color: #ffffff;
  padding: 10px;
  padding-left: 35px;
  margin: -10px 0;
  border-top: 10px solid #f0eded;
  border-bottom: 10px solid #f0eded;
}
 
.section_8bit::before,
.section_8bit::after,
.section_8bit .wrapper::before,
.section_8bit .wrapper::after{
  content: '';
  width: 10px;
  height: 10px;
  display: block;
  position: absolute;
  background: #f0eded;
}
.section_8bit::before{ top: -5px; left: -5px; }
.section_8bit::after{ top: -5px; right: -5px; }
.section_8bit .wrapper::before{ bottom: -5px; left: -5px; }
.section_8bit .wrapper::after{ bottom: -5px; right: -5px; }

.button-arrow-right {
  color: #000000;
  position: absolute;
  bottom: 51%;
  box-sizing: border-box;
  font-size: 100px;
  text-decoration: none;
  right: 20px;

}

.button-arrow-right:hover, .button-arrow-right:active{
  color: #000000;
  text-decoration: none;
}

.button-arrow-left {
  color: #000000;
  position: absolute;
  bottom: 51%;
  box-sizing: border-box;
  font-size: 100px;
  text-decoration: none;
  left: 20px;

}

.button-arrow-left:hover, .button-arrow-left:active{
  color: #000000;
  text-decoration: none;
}
#container{
  position: absolute;
  height: 100%;
  width: 100%;
  background-image: url("Brauciens.png");
  background-size: cover;
}
</style>
<div id="container">
<section class="outer">
<section class="section_8bit">
  <div class="wrapper">
    <h1><%= t 'ride' %></h1>
    <p> <%= t 'ride_desc' %> </p>
  </div>
</section>

<%= link_to ">", level2_path, method: :get, class: "button-arrow-right" %>
<%= link_to "<", level4_path, method: :get, class: "button-arrow-left" %>
</section>
</div>

app/views/levels/level4.html.erb
<style>
.outer{
    padding: 30px;
}

.section_8bit{
  font-size: 19px;
  width: 95%;
  float: left;
  height: 15%;
  border-left: 10px solid #f0eded;
  border-right: 10px solid #f0eded;
  position: absolute;
  bottom: 4%;
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
  background: #000000;
  overflow:auto;
}
 
.section_8bit .wrapper{
  display: block;
  color: #ffffff;
  padding: 10px;
  padding-left: 35px;
  margin: -10px 0;
  border-top: 10px solid #f0eded;
  border-bottom: 10px solid #f0eded;
}
 
.section_8bit::before,
.section_8bit::after,
.section_8bit .wrapper::before,
.section_8bit .wrapper::after{
  content: '';
  width: 10px;
  height: 10px;
  display: block;
  position: absolute;
  background: #f0eded;
}
.section_8bit::before{ top: -5px; left: -5px; }
.section_8bit::after{ top: -5px; right: -5px; }
.section_8bit .wrapper::before{ bottom: -5px; left: -5px; }
.section_8bit .wrapper::after{ bottom: -5px; right: -5px; }

.button-arrow-right {
  color: #000000;
  position: absolute;
  bottom: 51%;
  box-sizing: border-box;
  font-size: 100px;
  text-decoration: none;
  right: 20px;

}

.button-arrow-right:hover, .button-arrow-right:active{
  color: #000000;
  text-decoration: none;
}

.button-arrow-left {
  color: #000000;
  position: absolute;
  bottom: 51%;
  box-sizing: border-box;
  font-size: 100px;
  text-decoration: none;
  left: 20px;

}

.button-arrow-left:hover, .button-arrow-left:active{
  color: #000000;
  text-decoration: none;
}
#container{
  position: absolute;
  height: 100%;
  width: 100%;
  background-image: url("Vermanes_Darzs(1).png");
  background-size: cover;
  overflow:auto;
}
</style>
<div id="container">
<section class="outer">
<section class="section_8bit">
  <div class="wrapper">
    <h1><%= t 'garden' %></h1>
    <p><%= t 'garden_desc' %> </p>
  </div>
</section>

<%= link_to ">", level3_path, method: :get, class: "button-arrow-right" %>
<%= link_to "<", level5_path, method: :get, class: "button-arrow-left" %>
</section>
</div>

app/views/levels/level5.html.erb
<style>
.outer{
    padding: 30px;
}

.section_8bit{
  font-size: 19px;
  width: 95%;
  height: 15%;
  float: left;
  border-left: 10px solid #f0eded;
  border-right: 10px solid #f0eded;
  position: absolute;
  bottom: 4%;
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
  background: #000000;
  overflow:auto;
}
 
.section_8bit .wrapper{
  display: block;
  color: #ffffff;
  padding: 10px;
  padding-left: 35px;
  margin: -10px 0;
  border-top: 10px solid #f0eded;
  border-bottom: 10px solid #f0eded;
}
 
.section_8bit::before,
.section_8bit::after,
.section_8bit .wrapper::before,
.section_8bit .wrapper::after{
  content: '';
  width: 10px;
  height: 10px;
  display: block;
  position: absolute;
  background: #f0eded;
}
.section_8bit::before{ top: -5px; left: -5px; }
.section_8bit::after{ top: -5px; right: -5px; }
.section_8bit .wrapper::before{ bottom: -5px; left: -5px; }
.section_8bit .wrapper::after{ bottom: -5px; right: -5px; }

.button-arrow-right {
  color: #000000;
  position: absolute;
  bottom: 51%;
  box-sizing: border-box;
  font-size: 100px;
  text-decoration: none;
  right: 20px;

}

.button-arrow-right:hover, .button-arrow-right:active{
  color: #000000;
  text-decoration: none;
}

.button-arrow-left {
  color: #000000;
  position: absolute;
  bottom: 51%;
  box-sizing: border-box;
  font-size: 100px;
  text-decoration: none;
  left: 20px;

}

.button-arrow-left:hover, .button-arrow-left:active{
  color: #000000;
  text-decoration: none;
}
#container{
  position: absolute;
  height: 100%;
  width: 100%;
  background-image: url("Dabas_Muzejs(1).png");
  background-size: cover;
  overflow:auto;
}
</style>
<div id="container">
<section class="outer">
<section class="section_8bit">
  <div class="wrapper">
    <h1><%= t 'museum' %></h1>
    <p> <%= t 'museum_desc' %> </p>
  </div>
</section>

<%= link_to ">", level4_path, method: :get, class: "button-arrow-right" %>
<%= link_to "<", level7_path, method: :get, class: "button-arrow-left" %>
</section>
</div>

app/views/levels/level7.html.erb
<style>
.outer{
    padding: 30px;
}

.section_8bit{
  font-size: 19px;
  width: 95%;
  float: left;
  height: 15%;
  border-left: 10px solid #f0eded;
  border-right: 10px solid #f0eded;
  position: absolute;
  bottom: 4%;
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
  background: #000000;
  overflow:auto;
}
 
.section_8bit .wrapper{
  display: block;
  color: #ffffff;
  padding: 10px;
  padding-left: 35px;
  margin: -10px 0;
  border-top: 10px solid #f0eded;
  border-bottom: 10px solid #f0eded;
}
 
.section_8bit::before,
.section_8bit::after,
.section_8bit .wrapper::before,
.section_8bit .wrapper::after{
  content: '';
  width: 10px;
  height: 10px;
  display: block;
  position: absolute;
  background: #f0eded;
}
.section_8bit::before{ top: -5px; left: -5px; }
.section_8bit::after{ top: -5px; right: -5px; }
.section_8bit .wrapper::before{ bottom: -5px; left: -5px; }
.section_8bit .wrapper::after{ bottom: -5px; right: -5px; }

.button-arrow-right {
  color: #000000;
  position: absolute;
  bottom: 51%;
  box-sizing: border-box;
  font-size: 100px;
  text-decoration: none;
  right: 20px;

}

.button-arrow-right:hover, .button-arrow-right:active{
  color: #000000;
  text-decoration: none;
}

.button-arrow-left {
  color: #000000;
  position: absolute;
  bottom: 51%;
  box-sizing: border-box;
  font-size: 100px;
  text-decoration: none;
  left: 20px;

}

.button-arrow-left:hover, .button-arrow-left:active{
  color: #000000;
  text-decoration: none;
}
#container{
  position: absolute;
  height: 100%;
  width: 100%;
  background-image: url("Latvijas_Universitate2.png");
  background-size: cover;
}
</style>
<div id="container">
<section class="outer">
<section class="section_8bit">
  <div class="wrapper">
    <h1><%= t 'uni' %></h1>
    <p><%= t 'uni_desc' %></p>
  </div>
</section>

<%= link_to ">", level5_path, method: :get, class: "button-arrow-right" %>
<%= link_to "<", home_path, method: :get, class: "button-arrow-left" %>
</section>
</div>